### ISSUE TITLE
Project pitch

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/metanorma.com#2]
The pitch follows tagline on our Open Project site’s main page hero unit.

Tagline for Metanorma was already provided on Ricardo’s design mock-ups as “We have made the standards of standards tool”. However, the pitch was merely a placeholder.

Let’s brainstorm the pitch for Metanorma! Perhaps a good candidate already exists somewhere in the documentation, or perhaps we can come up with something.

Per designs we have, I _estimate_ the pitch should be 1–2 sentences and 10–18 words total. Anything too far out of these bounds may not look great, but we can play with typography to a degree, so anyway there’re no wrong answers here.

<img width="1395" alt="screen shot 2018-07-01 at 7 32 46 pm" src="https://user-images.githubusercontent.com/292959/42134413-8f9cabe2-7d65-11e8-8592-67aa4e397e8f.png">

**Comment by opoudjis** [comment]
A robust document workflow for standards.

Because standards documents are too important to manage in Word

Manage your standards documents like you manage your standards

What You See Is What You Need

**Comment by strogonoff** [comment]
@opoudjis 

I went ahead and put “Because standards documents are too important to manage in Word” there for now as it sounds compelling and tangible. (We can iterate on phrasing if e.g. referring to Microsoft’s product would turn out to be a problem.)

I also liked the “Manage your standards documents like you manage your standards” version but we currently have “the standards of standards tool” in tagline so I figured we’d save one repetition of the word “standards” 😂

Thanks for the help, the gist of Metanorma is a bit tough to grasp for me from the outside as it’s not a specific piece of software like some other open projects.

**Comment by opoudjis** [comment]
I feel I should spend some time explaining the motivation, but I feel that's kind of more @ronaldtse's job. Some articulations of the value proposition, we have already written:  of the stuff I've written, I'd refer you to https://github.com/riboseinc/asciidoctor-iso#approach, and https://github.com/riboseinc/rfc-asciidoc-rfc/blob/master/sections/01-intro.adoc. 

* The approach shares the arguments against WYSIWYG documents in general: decoupling formatting and rendering from content is a good thing, and introduces flexibility. 
* It also expedites the authoring process, which is particularly critical in standards—documents that are written by committee. Collaborative document editing is much more difficult in Word than in text-based systems (or in very simple WYSIWYG systems, such as Google Docs): much more goes wrong with Word, and versioning is much harder to track. (Hence the tag line you've adopted.)
* Standards documents are very fixed in their structure. The fact that we are generating an intermediate XML representation of the document is of particular benefit for standards, because most of the rules on how to author a standards document can be captured as structure rules, and validated through a schema. And a machine is always going to be better about capturing errors than humans.

@ronaldtse You have a Powerpoint worth sharing with Anton making the argument for Metanorma: the ISO standards error-checking process is anecdotally so broken, that subcommittees have agreed to always veto final drafts, in order to force additional proofreading before the standard is published.

The argument this is making is for a non-WYSIWYG document authoring system for standards in particular, with their fixed structure. For generic documents, even Word, the non-WYSIWYG authoring system niche is already taken by several offerings: DocBook used to be one, and now it's either TeX, or HTML. (Asciidoctor and Markdown to a somewhat lesser extent.) I don't know what's underneath Google Docs, but I strongly suspect it's just HTML.

Of course, WYSIWYG systems will never go away, and they have clear advantages; you only want to advocate for a setup like Metanorma in contexts where the advantages of Metanorma are higher (automatic validation, less risk of document corruption, collaborative authoring, multiple output formats) than the advantages of Word. Those advantages are much more obvious in standards bodies, and other kinds of document that have a fixed structure. Ronald is extending Metanorma to business documents; he'll have to argue this case further.

**Comment by strogonoff** [comment]
Thank you @opoudjis, this explains a lot. Accidentally clicked wrong reaction at first.

Is “non-WYSIWYG document authoring system for standards” one of correct descriptions for Metanorma? (also cc @ronaldtse)

asciidoctor-iso and rfc-asciidoctor-rfc docs are great, though they aren’t about Metanorma as the larger umbrella initiative per se.

README at https://github.com/riboseinc/metanorma is better. I do have to spend some time learning about business applications of Metanorma, and more time wrapping my head around the challenges standards bodies are facing (they aren’t a customer whom I can easily understand), to be able to describe the project from the right perspective in site copy.
