### ISSUE TITLE
Document how to insert official "comments"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#39]
This isn't documented anywhere, it seems?

ping @opoudjis 

```adoc
==== Localization Information (LocalizationInformation)

[source=Foo Bar]
****
Move encoding to Annex.
****
```

**Comment by opoudjis** [comment]
https://github.com/riboseinc/metanorma-standoc#reviewer-notes

I refactored the readme of https://github.com/riboseinc/metanorma-iso: all the Asciidoctor customisations that were in metanorma-iso but which apply to the entire stack are now given in tghe metanorma-standoc README. 

The Asciidoctor customisations listed in the metanorma-standoc README may or may not be elsewhere in the documentation stack; I am no longer maintaining that, so that becomes @strogonoff's issue...
